version: '3.7'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  frontend:
    build: ./frontend
    command: npm run serve
    volumes:
        - './frontend:/app'
    ports:
        - '8080:8080'
volumes:
  postgres_db: