# Generated by Django 3.2.3 on 2021-05-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_link', models.CharField(max_length=10)),
                ('url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='short', to='url_shortener_app.url')),
            ],
        ),
        migrations.CreateModel(
            name='CustomShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_short_link', models.CharField(max_length=100, unique=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='custom_short', to='url_shortener_app.url')),
            ],
        ),
    ]
